spring:
  datasources:
  - name: LOJA1
    url: ${DB_URL}/loja1
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    dbInstance: loja1
  - name: LOJA2
    url: ${DB_URL}/loja2
    username:  ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    dbInstance: loja2

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

  flyway:
    out-of-order: true


jwt:
  secret: ${JWT_KEY}